### ISSUE TITLE
Latest Follower

### ISSUE THREAD

**Issue by firmai** [xcaq/xcaq#1]
Hi, nice readme, I am a little bit dumbstruck, your latest follower element is nice, but I have not idea how you did it (are doing it?)

**Comment by xcaq** [comment]
Hey Derek. Thanks :) I'm using the GitHub API method `/user/followers`.

**Comment by xcaq** [comment]
Check this out https://docs.github.com/en/rest/reference/users#list-followers-of-the-authenticated-user.

**Comment by firmai** [comment]
Thanks thats great!!
