### ISSUE TITLE
Collab and improving README

### ISSUE THREAD

**Issue by debugleader** [xcaq/xcaq#1]
Hey, how are you?
I saw that you were talking about a collab so I thought about asking if you're willing to work on python projects together.
Also, I can help to improve your README files and try to contribute and fix issues for your projects if you need me. @xcaq 
My email is : [email address.](mailto:alkhassakyabdallah@gmail.com)

**Comment by xcaq** [comment]
Hey 👋🏻. Maybe we can do something, message me in [telegram](https://t.me/xxcaq).

**Comment by debugleader** [comment]
I don't have telegram, if you want, email me here [email](mailto:alkhassakyabdallah@gmail.com).
